source "https://rubygems.org"

gem 'rack'
gem 'sinatra'

# START:concurrent
gem 'concurrent-ruby', require: 'concurrent'
# END:concurrent

# START:warbler
group :development do
  gem 'warbler', '2.1.0'
end
# END:warbler
